spring.application.name=jws-generator
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true

# Application info
info.app.name=JWS Generator
info.app.description=Spring Boot application for generating JSON Web Signatures
info.app.version=0.0.1-SNAPSHOT
